# Generated by Django 4.1.5 on 2023-06-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('father_name', models.CharField(max_length=35)),
                ('mother_name', models.CharField(max_length=35)),
                ('address', models.TextField()),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
