# Generated by Django 4.1.5 on 2023-06-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.guest'),
        ),
    ]
