# Generated by Django 4.1.5 on 2023-06-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deptt', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('doj', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
